### ISSUE TITLE
Lots of data to cache

### ISSUE THREAD

**Issue by goutomroy** [atodorov/django-s3-cache#3]
Firstly thank you for your very useful library.
I have 20,00000 JSON strings each one 35kb, total 66GB. 
From my django app there will be lots of get operation.
Will it be a good idea using this library for my purpose.

Thanks in advance.

**Comment by atodorov** [comment]
Nope, pulling 60G in and out of Amazon S3 will be very slow. It's like reading a 60G file from a spinning disk.
